set(CMAKE_SYSTEM_NAME Windows)
set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)


FIND_PROGRAM(CMAKE_C_COMPILER NAMES x86_64-w64-mingw32-gcc)
FIND_PROGRAM(CMAKE_CXX_COMPILER NAMES x86_64-w64-mingw32-g++)
FIND_PROGRAM(CMAKE_RC_COMPILER_INIT NAMES x86_64-w64-mingw32-windres)
FIND_PROGRAM(CMAKE_AR NAMES x86_64-w64-mingw32-ar)

# target environment on the build host system
set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})

# modify default behavior of FIND_XXX() commands
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_CROSS_COMPILING TRUE)
